--Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount_usd) AS revenue
FROM orders
GROUP BY gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id, purchase_amount_usd
FROM orders
WHERE discount_applied = 'Yes' 
      AND purchase_amount_usd > (SELECT ROUND(AVG(purchase_amount_usd),2)FROM orders);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased AS product, ROUND(AVG(review_rating::numeric),2)  AS mean_review 
FROM orders
GROUP BY product
ORDER BY mean_review DESC
LIMIT 5;
-- ROUND(AVG(review_rating::numeric),2) || CAST(AVG(review_rating) AS DECIMAL(12,2))

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type, ROUND(AVG(purchase_amount_usd::numeric),2) FROM orders
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

/*Q5. Do subscribed customers spend more? Compare average spend and total revenue 
between subscribers and non-subscribers. */
SELECT subscription_status, COUNT(subscription_status) AS no_of_customers,
ROUND(AVG(purchase_amount_usd::numeric),2) AS avg_spent,
ROUND(SUM(purchase_amount_usd::numeric),2) AS total_spent
FROM orders 
GROUP BY subscription_status
ORDER BY avg_spent DESC, total_spent DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT 
item_purchased,
ROUND((100.0* SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END )/COUNT(*)),2) AS orders_percetage
FROM orders
GROUP BY item_purchased
ORDER BY orders_percetage DESC
LIMIT 5;

/*Q7. Segment customers into New, Returning, and Loyal based on their total 
number of previous purchases, and show the count of each segment. */

WITH customer_cte AS (SELECT *,
CASE WHEN previous_purchases = 1 THEN 'New'
     WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	 WHEN previous_purchases > 10 THEN 'Loyal'
	 ELSE 'Others'
	 END AS customer_category
FROM orders)
SELECT customer_category, COUNT(customer_category) AS no_of_customers FROM customer_cte 
GROUP BY customer_category
ORDER BY no_of_customers DESC;

--Q8. What are the top 3 most purchased products within each category? 

WITH product_summary AS 
(SELECT item_purchased, category, COUNT(customer_id) AS no_of_orders,
DENSE_RANK() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) as product_rnk
FROM orders
GROUP BY item_purchased, category)

SELECT * FROM product_summary 
WHERE product_rnk <=3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) AS customers FROM orders
WHERE previous_purchases > 5
GROUP BY subscription_status
ORDER BY customers DESC;

--Q10. What is the revenue contribution of each age group? 
SELECT age_group, SUM(purchase_amount_usd) AS total_revenue FROM orders
GROUP BY age_group
ORDER BY total_revenue DESC;
